dataset_name: Reconbench
dataset_root: /mnt/raphael/reconbench
save_dir: /mnt/raphael/ShapeNet_out/benchmark/poco/tr
gen_dir: reconbench

classes: null
scan: 4
manifold_points: 3000
non_manifold_points: 2048
random_noise: 0.0

gen_resolution_global: 128

iter_nbr: 600000

