config: configs/config_modelnet_viewpoint.yaml
config_default: configs/config_default.yaml
dataset_name: ModelNetViewpoints
dataset_root: /mnt/raphael/ModelNet10
device: cuda:1
experiment_name: withSensorAP
filter_name: null
iter_nbr: 600000
log_mode: interactive
logging: INFO
manifold_points: 3000
network_backbone: FKAConvAP
network_decoder: InterpAttentionKHeadsNet
network_decoder_k: 64
network_latent_size: 32
network_n_labels: 2
non_manifold_points: 2048
normals: true
random_noise: 0.0
resume: false
save_dir: /mnt/raphael/ModelNet10_out/poco
test_split: test
threads: 8
train_split: training
training_batch_size: 16
training_iter_nbr: 100000
training_lr_start: 0.001
training_random_rotation_x: null
training_random_rotation_y: null
training_random_rotation_z: null
training_random_scale: null
val_interval: 1
val_num_mesh: null
val_split: validation
